kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: ninja-board
  namespace: giveback--build
spec:
  nodeSelector: null
  output:
    to:
      kind: DockerImage
      name: 'images.paas.redhat.com/giveback/ninja-board:latest'
    pushSecret:
      name: images-paas-push-config
  postCommit: {}
  resources: {}
  runPolicy: Serial
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: giveback--build
        name: 'ninja-board-base:latest'
  source:
    type: Git
    git:
      uri: 'https://github.com/redhat-cop/ninja-board.git'
      ref: v1.27
  triggers:
    - type: ImageChange
      imageChange:
    - type: ConfigChange
