kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: ninja-graphs
  namespace: giveback--build
spec:
  nodeSelector: null
  output:
    to:
      kind: DockerImage
      name: 'images.paas.redhat.com/giveback/ninja-graphs:latest'
    pushSecret:
      name: images-paas-push-config
  postCommit: {}
  resources: {}
  runPolicy: Serial
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'jboss-webserver31-tomcat7-openshift:1.1'
  source:
    type: Git
    git:
      uri: 'https://github.com/matallen/ninja-graphs.git'
      ref: master
  triggers:
    - type: ImageChange
      imageChange:
    - type: ConfigChange
