apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: giveback--build
commonLabels:
  app.kubernetes.io/name: ninja-board
  app.kubernetes.io/component: build
  paas.redhat.com/appcode: GVBK-001
resources:
- ImageStream-ninja-board-base.yml
- BuildConfig-ninja-board-base.yml
- BuildConfig-ninja-board.yml