kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    app.openshift.io/vcs-ref: v1.27
    app.openshift.io/vcs-uri: 'https://github.com/redhat-cop/ninja-board'
    deployment.kubernetes.io/revision: '1'
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"ninja-board:latest","namespace":"giveback--preprod"},"fieldPath":"spec.template.spec.containers[?(@.name==\"ninja-board\")].image","pause":"false"}]
  resourceVersion: '263381065'
  name: ninja-board
  uid: 628cfb31-8b3e-4dd0-8c61-fa060f46ff87
  creationTimestamp: '2022-02-16T19:34:01Z'
  generation: 2
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: apps/v1
      time: '2022-02-16T19:34:01Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:alpha.image.policy.openshift.io/resolve-names': {}
            'f:app.openshift.io/vcs-ref': {}
            'f:app.openshift.io/vcs-uri': {}
            'f:image.openshift.io/triggers': {}
          'f:labels':
            .: {}
            'f:app': {}
            'f:app.kubernetes.io/component': {}
            'f:app.kubernetes.io/instance': {}
            'f:app.kubernetes.io/name': {}
            'f:app.kubernetes.io/part-of': {}
            'f:app.openshift.io/runtime': {}
            'f:app.openshift.io/runtime-version': {}
        'f:spec':
          'f:progressDeadlineSeconds': {}
          'f:replicas': {}
          'f:revisionHistoryLimit': {}
          'f:selector': {}
          'f:strategy':
            'f:rollingUpdate':
              .: {}
              'f:maxSurge': {}
              'f:maxUnavailable': {}
            'f:type': {}
          'f:template':
            'f:metadata':
              'f:labels':
                .: {}
                'f:app': {}
                'f:deploymentconfig': {}
            'f:spec':
              'f:containers':
                'k:{"name":"giveback-prod"}':
                  'f:image': {}
                  'f:volumeMounts':
                    .: {}
                    'k:{"mountPath":"/home/jboss"}':
                      .: {}
                      'f:mountPath': {}
                      'f:name': {}
                      'f:subPath': {}
                  'f:terminationMessagePolicy': {}
                  .: {}
                  'f:resources': {}
                  'f:env':
                    'k:{"name":"TRELLO_API_TOKEN"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"USERS_LDAP_PROVIDER"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"SMARTSHEETS_API_TOKEN"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"TRELLO_API_KEY"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    .: {}
                    'k:{"name":"GITLAB_API_TOKEN"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"GRAPHS_PROXY"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"GITHUB_API_TOKEN"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"GD_CREDENTIALS"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                  'f:terminationMessagePath': {}
                  'f:imagePullPolicy': {}
                  'f:ports':
                    .: {}
                    'k:{"containerPort":8080,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:protocol': {}
                    'k:{"containerPort":8443,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:protocol': {}
                    'k:{"containerPort":8778,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:protocol': {}
                  'f:name': {}
              'f:dnsPolicy': {}
              'f:restartPolicy': {}
              'f:schedulerName': {}
              'f:securityContext': {}
              'f:terminationGracePeriodSeconds': {}
              'f:volumes':
                .: {}
                'k:{"name":"giveback-prod-storage"}':
                  .: {}
                  'f:name': {}
                  'f:persistentVolumeClaim':
                    .: {}
                    'f:claimName': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2022-02-16T19:45:20Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:deployment.kubernetes.io/revision': {}
        'f:status':
          'f:conditions':
            .: {}
            'k:{"type":"Available"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Progressing"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
          'f:observedGeneration': {}
  namespace: giveback--prod
  labels:
    app: ninja-board
    app.kubernetes.io/component: ninja-board
    app.kubernetes.io/instance: ninja-board
    app.kubernetes.io/name: java
    app.kubernetes.io/part-of: giveback
    app.openshift.io/runtime: java
    app.openshift.io/runtime-version: openjdk-11-el7
spec:
  replicas: 0
  selector:
    matchLabels:
      app: ninja-board
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ninja-board
        deploymentconfig: ninja-board
    spec:
      volumes:
        - name: giveback-prod-storage
          persistentVolumeClaim:
            claimName: giveback-prod-storage
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: giveback-prod
          env:
            - name: GITHUB_API_TOKEN
              value: 7935781f5b2c74302f91d3274736958cf2521438
            - name: TRELLO_API_TOKEN
              value: 85e332445c4d221e09ecd0d1309a795c4f6aa0b99249852d896d3cee1f235610
            - name: TRELLO_API_KEY
              value: 39cca1583d34154be24aa99ee024106d
            - name: GITLAB_API_TOKEN
              value: sacCXjRwS9mDcKQsJJFC
            - name: SMARTSHEETS_API_TOKEN
              value: 7o8djelr503ekzb4phyje3wvoh
            - name: GD_CREDENTIALS
              value: >-
                {"access_token":
                "ya29.GlxsB54BamYjni1ZZGLfOW2MhlOQuJA2Mh4sEMHWaUYJNntKiYL6v42ivmP9EXInBetcaTltbbjcsqOLLuT8jA0ucBUBEmYNahCdqanPtLGIYKjueuSBCmAz2yakzA",
                "token_type": "Bearer", "refresh_token":
                "1/dktL5rchPlNJlY7CezrMp3cBt4k6j8Tx_5NLGmkA8D5yO1KqDR0_gWOTosp3H-wx",
                "expiry": "2019-08-22T13:48:25.666651305-05:00"}
            - name: GRAPHS_PROXY
              value: >-
                http://ninja-graphs-ninja-graphs.6923.rh-us-east-1.openshiftapps.com/ninja-graphs
            - name: USERS_LDAP_PROVIDER
              value: 'ldap://ldap.corp.redhat.com:389'
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
            - containerPort: 8778
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: giveback-prod-storage
              mountPath: /home/jboss
              subPath: target/ninja-persistence
          terminationMessagePolicy: File
          image: 'images.paas.redhat.com/giveback/ninja-board:latest'
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 2
  conditions:
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2022-02-16T19:34:22Z'
      lastTransitionTime: '2022-02-16T19:34:01Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "ninja-board-5966947595" has successfully progressed.
    - type: Available
      status: 'True'
      lastUpdateTime: '2022-02-16T19:45:20Z'
      lastTransitionTime: '2022-02-16T19:45:20Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
