apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: giveback-prod-storage
  namespace: giveback--prod
  labels:
    paas.redhat.com/appcode: GVBK-001
  annotations:
    kubernetes.io/reclaimPolicy: Delete
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: aws-efs-tier-c3