kind: Service
apiVersion: v1
metadata:
  name: ninja-board
  namespace: giveback--prod
  labels:
    app: metrics
    app.kubernetes.io/component: ninja-board
    app.kubernetes.io/instance: ninja-board
    app.kubernetes.io/name: java
    app.kubernetes.io/part-of: giveback
    app.openshift.io/runtime: java
    app.openshift.io/runtime-version: openjdk-11-el7
  annotations:
    app.openshift.io/vcs-ref: master
    app.openshift.io/vcs-uri: >-
      https://github.com/redhat-cop/ninja-board
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: 8443-tcp
      protocol: TCP
      port: 8443
      targetPort: 8443
    - name: 8778-tcp
      protocol: TCP
      port: 8778
      targetPort: 8778
  selector:
    app: ninja-board
    deploymentconfig: ninja-board
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
status:
  loadBalancer: {}
