kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: ninja-graphs
  namespace: giveback--graphs-ext
  labels:
    app: ninja-graphs
    app.kubernetes.io/component: ninja-graphs
    app.kubernetes.io/instance: ninja-graphs
    app.kubernetes.io/name: java
    app.kubernetes.io/part-of: giveback
    app.openshift.io/runtime: java
    app.openshift.io/runtime-version: openjdk-11-el7
    shard: ext-waf
spec:
  host: ninja-graphs-giveback--graphs-ext.apps.ext-waf.spoke.prod.us-east-1.aws.paas.redhat.com
  to:
    kind: Service
    name: ninja-graphs
    weight: 100
  port:
    targetPort: 8080-tcp
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow
  wildcardPolicy: None
